root: true

env:
  node: true
  es6: true

extends:
  - plugin:vue/recommended
  - eslint:recommended
  - plugin:prettier/recommended

ignorePatterns:
  - node_modules/
  - packages/@vuepress/shared-utils/lib
  - packages/@vuepress/shared-utils/types

overrides:
  - files:
      - "*.ts"

    extends:
      - plugin:@typescript-eslint/eslint-recommended
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
      - plugin:prettier/recommended

    plugins:
      - "@typescript-eslint"

    parser: vue-eslint-parser

    parserOptions:
      parser: "@typescript-eslint/parser"
      project:
        - "./tsconfig.json"
        - "./tsconfig.eslint.json"

    rules:
      "@typescript-eslint/explicit-function-return-type":
        - warn
        - allowTypedFunctionExpressions: true

      "@typescript-eslint/naming-convention":
        - warn
        - selector: default
          format:
            - camelCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - variable
          format:
            - camelCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - parameter
          format:
            - camelCase
            - PascalCase
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector:
            - property
          format:
            - camelCase
            - PascalCase
            - UPPER_CASE
          leadingUnderscore: allow
          trailingUnderscore: allow

        - selector: typeLike
          format:
            - PascalCase

      "@typescript-eslint/no-explicit-any":
        - warn
        - ignoreRestArgs: true

      "@typescript-eslint/no-unsafe-argument":
        - warn

      "@typescript-eslint/no-unsafe-assignment":
        - warn

      "@typescript-eslint/no-unsafe-member-access":
        - warn

      "@typescript-eslint/no-unsafe-return":
        - warn

      "@typescript-eslint/no-unsafe-call":
        - warn

      "@typescript-eslint/restrict-template-expressions":
        - warn

  - files:
      - "**/__tests__/**/*.spec.{j,t}s?(x)"

    env:
      jest: true

    rules:
      "@typescript-eslint/naming-convention":
        - off
      "@typescript-eslint/no-explicit-any":
        - off
      "@typescript-eslint/no-unsafe-assignment":
        - off
      "@typescript-eslint/no-non-null-assertion":
        - off
      "@typescript-eslint/no-unsafe-call":
        - off
      "@typescript-eslint/no-unsafe-member-access":
        - off
